import json
import logging
from app.services.llm_client import LLMClient

logger = logging.getLogger(__name__)

client = LLMClient()


# ✅ Normalize action to allowed enum
def _normalize_action(action: str) -> str:
    action = action.lower()

    if "read" in action:
        return "read"
    if "write" in action or "assign" in action or "update" in action or "initialize" in action:
        return "write"
    if "compare" in action or "if" in action:
        return "compare"
    if "call" in action:
        return "call"
    if "return" in action:
        return "return"

    return "write"  # safe fallback


def build_prompt(code: str, problem_type: str) -> str:
    return f"""
You are a deterministic C++ execution engine.

STRICT REQUIREMENTS:
- Output ONLY valid JSON
- NO markdown
- NO explanation
- NO text outside JSON
- JSON must be parseable by Python json.loads()

SCHEMA:
{{
  "initial_state": {{
    "variables": {{}}
  }},
  "steps": [
    {{
      "line": int,
      "action": "read/write/compare/call/return",
      "variables": {{}}
    }}
  ],
  "has_crash": false,
  "error": null
}}

RULES:
- Track ALL variables after each step
- Arrays must be fully shown after modification
- Each step = ONE execution event
- Maintain correct execution order
- DO NOT skip steps
- DO NOT summarize

LIMITS:
- Maximum 50 steps
- Keep output concise
- Avoid redundant steps

C++ CODE:
{code}
"""


def _clean_json(text: str) -> str:
    text = text.strip()

    if text.startswith("```"):
        parts = text.split("```")
        if len(parts) >= 2:
            text = parts[1]

    return text.strip()


def _parse_json(text: str) -> dict:
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        cleaned = _clean_json(text)
        return json.loads(cleaned)


# ✅ Transform LLM output → your schema
def _transform_steps(raw_steps: list) -> list:
    transformed = []

    for i in range(len(raw_steps)):
        step = raw_steps[i]

        transformed.append({
            "stepNumber": i + 1,
            "lineNumber": step.get("line", 0),
            "lineOfCode": "",  # placeholder (can improve later)
            "action": _normalize_action(step.get("action", "")),
            "variables": step.get("variables", {})
        })

    return transformed


async def create_trace(code: str, problem_type: str):
    prompt = build_prompt(code, problem_type)

    try:
        raw = await client.generate(prompt)

        # Debug log
        logger.info(f"LLM RAW LENGTH: {len(raw)}")

        parsed = _parse_json(raw)

        # ✅ HARD VALIDATION
        if "steps" not in parsed:
            raise ValueError("Missing 'steps'")

        if not isinstance(parsed["steps"], list):
            raise ValueError("'steps' must be a list")

        if len(parsed["steps"]) > 100:
            raise ValueError("Too many steps generated by LLM")

        # 🔥 CRITICAL FIX: transform here
        steps = _transform_steps(parsed["steps"])

        return {
            "initial_state": parsed.get("initial_state", {}),
            "trace_data": steps,
            "has_crash": parsed.get("has_crash", False),
            "error": parsed.get("error", None),
        }

    except Exception as e:
        logger.error("Trace generation failed")
        logger.error(str(e))

        return {
            "initial_state": {},
            "trace_data": [],
            "has_crash": True,
            "error": str(e),
        }